export type Erc8004Agent = {
  id: string;
  agent_id: string;
  token_id: string;
  chain_id: number;
  chain_type: string;
  contract_address: string;
  is_testnet: boolean;
  owner_address: string;
  owner_ens: string | null;
  owner_username: string | null;
  owner_avatar_url: string | null;
  owner_publisher_tier: string | null;
  owner_certified_name: string | null;
  name: string;
  description: string;
  image_url: string;
  is_verified: boolean;
  star_count: number;
  supported_protocols: string[];
  x402_supported: boolean;
  total_score: number;
  rank: number | null;
  health_score: number | null;
  total_feedbacks: number;
  average_score: number;
  cross_chain_versions: unknown[] | null;
  created_at: string;
  updated_at: string;
};
